---
platform: linux

image: docker:///kidikarus/cf-cli

inputs:
  - name: code-repo
  - name: code-release

run:
  path: code-repo/ci/tasks/cf-deployment.sh

params:
  API_ENDPOINT:
  USERNAME:
  PASSWORD:
  ORG:
  SPACE:
  HOST: